### ISSUE TITLE
Getting unhandled 'error' event

### ISSUE THREAD

**Issue by SunboX** [runk/node-thin#1]
Using your simple proxy example I'm getting this message:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1023:19)
    at listen (net.js:1064:10)
    at Server.listen (net.js:1132:5)
    at Mitm.listen (C:\xxx\node_modules\thin\lib\thin.js:30:57)
    at Object.<anonymous> (C:\xxx\proxy.js:18:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by olso** [comment]
+1
